name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Copy jar to cwd
      run: cp target/pincette-jes-http-*-jar-with-dependencies.jar app.jar
    - run: pwd && ls -la
    - name: Docker build
      env:
        AWS_ACCOUNTID_TARGET: ${{ secrets.AWS_ACCOUNTID_TARGET }}
        AWS_REGION: eu-central-1
      run: docker build -t ${AWS_ACCOUNTID_TARGET}.dkr.ecr.${AWS_REGION:-eu-central-1}.amazonaws.com/lemonade/pincette-jes-http .
    - name: AWS ECR Login
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCOUNTID_TARGET: ${{ secrets.AWS_ACCOUNTID_TARGET }}
        AWS_REGION: eu-central-1
      run: eval $(aws ecr get-login --no-include-email --region ${AWS_REGION:-eu-central-1})
    - name: Tag image
      env:
        AWS_ACCOUNTID_TARGET: ${{ secrets.AWS_ACCOUNTID_TARGET }}
        AWS_REGION: eu-central-1
      run: docker tag ${AWS_ACCOUNTID_TARGET}.dkr.ecr.${AWS_REGION:-eu-central-1}.amazonaws.com/lemonade/pincette-jes-http ${AWS_ACCOUNTID_TARGET}.dkr.ecr.${AWS_REGION:-eu-central-1}.amazonaws.com/lemonade/pincette-jes-http:latest
    - name: Push
      env:
        AWS_ACCOUNTID_TARGET: ${{ secrets.AWS_ACCOUNTID_TARGET }}
        AWS_REGION: eu-central-1
      run: docker push ${AWS_ACCOUNTID_TARGET}.dkr.ecr.${AWS_REGION:-eu-central-1}.amazonaws.com/lemonade/pincette-jes-http

  prepare-nonprod-config-repo:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
    - name: Create private key file ~/.ssh/id_rsa
      run: mkdir ~/.ssh && chmod 0700 ~/.ssh && printf -- "${SSH_PRIVATE_KEY}\n" > ~/.ssh/id-rsa && chmod 0600 ~/.ssh/id-rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Config git
      run: git config --global user.email "bitbucketpipeline@wherever.com" && git config --global user.name "Bitbucket Pipeline"
    - name: Load bitbucket.org host keys
      run: ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts && chmod 0600 ~/.ssh/known_hosts && ls -lR ~/.ssh && cat ~/.ssh/id-rsa
    - name: Check what git user is being used
      run: ssh git@bitbucket.org
    - name: Checkout config repo
      run: rm -rf remote_repo && git clone git@bitbucket.org:lemonade-git/pincette-jes-http.config.tst.git remote_repo
    - name: Create the TAG file
      run: cd remote_repo && echo "${GITHUB_SHA}" > TAG && git add TAG && git commit --allow-empty "Update TAG with source repo commit hash" && git push 

