name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Build Docker Image
      run: ls -lR
    - run: cp target/pincette-jes-http-*-jar-with-dependencies.jar app.jar
    - run: pwd && ls -la
    - run: docker build -t lemonade/pincette-jes-http .
    - name: AWS ECR Login
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-central-1
      run: eval $(aws ecr get-login --no-include-email --region ${AWS_REGION:-eu-central-1})
    - name: Push
      run: docker push lemonade/pincette-jes-http

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Deploy Artefact Container image to ECR
      run: echo "Placeholder"
